import { supabase } from '@/lib/supabase'

// =============================================
// EMPLOYEES
// =============================================

export async function getEmployees() {
  const { data, error } = await supabase
    .from('employees')
    .select(`
      *,
      departments(name),
      role_templates(name)
    `)
    .order('created_at', { ascending: false })

  if (error) throw error
  return data
}

export async function getEmployee(id: string) {
  const { data, error } = await supabase
    .from('employees')
    .select(`
      *,
      departments(name),
      role_templates(name, default_permissions),
      permissions(*, systems(name, is_critical))
    `)
    .eq('id', id)
    .single()

  if (error) throw error
  return data
}

export async function createEmployee(employee: {
  name: string
  email: string
  department_id: string
  role_template_id: string
  job_title: string
  join_date: string
}) {
  const { data, error } = await supabase
    .from('employees')
    .insert({
      ...employee,
      employee_id: '', // will be auto-generated by trigger
      jml_stage: 'joiner',
      status: 'pending',
    })
    .select()
    .single()

  if (error) throw error
  return data
}

export async function updateEmployee(id: string, updates: Record<string, any>) {
  const { data, error } = await supabase
    .from('employees')
    .update(updates)
    .eq('id', id)
    .select()
    .single()

  if (error) throw error
  return data
}

// =============================================
// PERMISSIONS  
// =============================================

export async function getEmployeePermissions(employeeId: string) {
  const { data, error } = await supabase
    .from('permissions')
    .select(`*, systems(name, is_critical, description)`)
    .eq('employee_id', employeeId)
    .order('created_at', { ascending: false })

  if (error) throw error
  return data
}

export async function revokePermission(permissionId: string) {
  const { data, error } = await supabase
    .from('permissions')
    .update({ is_active: false })
    .eq('id', permissionId)
    .select()
    .single()

  if (error) throw error
  return data
}

// =============================================
// SYSTEMS
// =============================================

export async function getSystems() {
  const { data, error } = await supabase
    .from('systems')
    .select('*')
    .order('name')

  if (error) throw error
  return data
}

// =============================================
// DEPARTMENTS & ROLE TEMPLATES
// =============================================

export async function getDepartments() {
  const { data, error } = await supabase
    .from('departments')
    .select('*')
    .order('name')

  if (error) throw error
  return data
}

export async function getRoleTemplates() {
  const { data, error } = await supabase
    .from('role_templates')
    .select(`*, departments(name)`)
    .order('name')

  if (error) throw error
  return data
}

// =============================================
// ACCESS REQUESTS
// =============================================

export async function getAccessRequests(filters?: { status?: string; employeeId?: string }) {
  let query = supabase
    .from('access_requests')
    .select(`
      *,
      employees(name, email, job_title),
      departments:employees(departments(name))
    `)
    .order('created_at', { ascending: false })

  if (filters?.status) query = query.eq('status', filters.status)
  if (filters?.employeeId) query = query.eq('employee_id', filters.employeeId)

  const { data, error } = await query
  if (error) throw error
  return data
}

export async function createAccessRequest(request: {
  employee_id: string
  request_type: string
  description?: string
  requested_permissions?: any[]
  priority?: string
}) {
  const { data, error } = await supabase
    .from('access_requests')
    .insert({
      ...request,
      request_number: '', // auto-generated
      status: 'pending',
    })
    .select()
    .single()

  if (error) throw error
  return data
}

export async function updateAccessRequest(id: string, updates: {
  status?: string
  reviewer_notes?: string
  reviewer_id?: string
}) {
  const { data, error } = await supabase
    .from('access_requests')
    .update({ ...updates, reviewed_at: new Date().toISOString() })
    .eq('id', id)
    .select()
    .single()

  if (error) throw error
  return data
}

// =============================================
// ACCESS REVIEWS
// =============================================

export async function getAccessReviews(filter?: string) {
  let query = supabase
    .from('access_reviews')
    .select(`
      *,
      employees(name, email, job_title),
      systems(name, is_critical)
    `)
    .order('created_at', { ascending: false })

  if (filter && filter !== 'all') {
    if (filter === 'pending') query = query.eq('decision', 'pending')
    else query = query.neq('decision', 'pending')
  }

  const { data, error } = await query
  if (error) throw error
  return data
}

export async function updateReviewDecision(id: string, decision: string, notes?: string) {
  const { data, error } = await supabase
    .from('access_reviews')
    .update({
      decision,
      notes,
      completed_date: new Date().toISOString().split('T')[0],
    })
    .eq('id', id)
    .select()
    .single()

  if (error) throw error
  return data
}

// =============================================
// AUDIT LOGS
// =============================================

export async function getAuditLogs(search?: string) {
  let query = supabase
    .from('audit_logs')
    .select('*')
    .order('created_at', { ascending: false })
    .limit(100)

  if (search) {
    query = query.or(`target_user_name.ilike.%${search}%,details.ilike.%${search}%,performed_by_name.ilike.%${search}%`)
  }

  const { data, error } = await query
  if (error) throw error
  return data
}

export async function createAuditLog(log: {
  action: string
  employee_id?: string
  performed_by_name: string
  target_user_name?: string
  details: string
  system_name?: string
  metadata?: any
}) {
  const { error } = await supabase.from('audit_logs').insert(log)
  if (error) console.error('Audit log error:', error)
}

// =============================================
// AI INSIGHTS
// =============================================

export async function getAiInsights(employeeId?: string) {
  let query = supabase
    .from('ai_insights')
    .select(`*, employees(name, email)`)
    .order('created_at', { ascending: false })

  if (employeeId) query = query.eq('employee_id', employeeId)

  const { data, error } = await query
  if (error) throw error
  return data
}

export async function resolveInsight(id: string) {
  const { data, error } = await supabase
    .from('ai_insights')
    .update({ is_resolved: true, resolved_at: new Date().toISOString() })
    .eq('id', id)
    .select()
    .single()

  if (error) throw error
  return data
}

// =============================================
// DASHBOARD STATS
// =============================================

export async function getDashboardStats() {
  // Fetch in parallel
  const [
    { count: totalUsers },
    { count: activeUsers },
    { count: highRiskUsers },
    { count: pendingReviews },
    { count: pendingRequests },
    { count: joiners },
    { count: movers },
    { count: leavers },
    { count: unresolvedInsights },
  ] = await Promise.all([
    supabase.from('employees').select('*', { count: 'exact', head: true }),
    supabase.from('employees').select('*', { count: 'exact', head: true }).eq('status', 'active'),
    supabase.from('employees').select('*', { count: 'exact', head: true }).in('risk_level', ['critical', 'high']),
    supabase.from('access_reviews').select('*', { count: 'exact', head: true }).eq('decision', 'pending'),
    supabase.from('access_requests').select('*', { count: 'exact', head: true }).eq('status', 'pending'),
    supabase.from('employees').select('*', { count: 'exact', head: true }).eq('jml_stage', 'joiner'),
    supabase.from('employees').select('*', { count: 'exact', head: true }).eq('jml_stage', 'mover'),
    supabase.from('employees').select('*', { count: 'exact', head: true }).eq('jml_stage', 'leaver'),
    supabase.from('ai_insights').select('*', { count: 'exact', head: true }).eq('is_resolved', false),
  ])

  // Get risk distribution
  const { data: riskData } = await supabase
    .from('employees')
    .select('risk_level')

  const riskDist = { critical: 0, high: 0, medium: 0, low: 0 }
  riskData?.forEach((e: any) => {
    if (e.risk_level in riskDist) riskDist[e.risk_level as keyof typeof riskDist]++
  })

  return {
    totalUsers: totalUsers ?? 0,
    activeUsers: activeUsers ?? 0,
    highRiskUsers: highRiskUsers ?? 0,
    pendingReviews: pendingReviews ?? 0,
    pendingRequests: pendingRequests ?? 0,
    joiners: joiners ?? 0,
    movers: movers ?? 0,
    leavers: leavers ?? 0,
    unresolvedInsights: unresolvedInsights ?? 0,
    riskDistribution: riskDist,
  }
}

// =============================================
// REALTIME SUBSCRIPTIONS
// =============================================

export function subscribeToEmployees(callback: () => void) {
  return supabase
    .channel('employees-changes')
    .on('postgres_changes', { event: '*', schema: 'public', table: 'employees' }, callback)
    .subscribe()
}

export function subscribeToRequests(callback: () => void) {
  return supabase
    .channel('requests-changes')
    .on('postgres_changes', { event: '*', schema: 'public', table: 'access_requests' }, callback)
    .subscribe()
}
